version: "3"

services:
  ingester:
    image: massimocodes/eth-archive-ingester:latest
    environment:
      RUST_LOG: "info"
    command: [
            "/eth/eth-archive-ingester",
            "--data-path", "/data/parquet/files",
            "--request-timeout-secs", "300",
            "--connect-timeout-ms", "1000",
            "--block-batch-size", "10",
            "--http-req-concurrency", "200",
            "--default-rpc-url", "http://host.docker.internal:8545/",
            # "--default-rpc-url", "https://rpc.ankr.com/eth_goerli",
            "--max-blocks-per-file", "100000",
            "--max-txs-per-file", "200000",
            "--max-logs-per-file", "200000",
    ]
    volumes:
      - parquet:/data
  worker:
    image: massimocodes/eth-archive-worker:latest
    environment:
      RUST_LOG: "info"
    ports:
      - 8080:8080
    command: [
            "/eth/eth-archive-worker",
            "--server-addr", "0.0.0.0:8080",
            "--db-path", "/data/db",
            "--data-path", "/data/parquet/files",
            "--request-timeout-secs", "300",
            "--connect-timeout-ms", "1000",
            "--block-batch-size", "10",
            "--http-req-concurrency", "200",
            "--default-rpc-url", "http://host.docker.internal:8545/",
            # "--default-rpc-url", "https://rpc.ankr.com/eth_goerli",
            "--min-hot-block-range", "100500",
            "--max-resp-body-size", "30",
            "--resp-time-limit", "5000",
    ]
    volumes:
      - db:/data/db
      - parquet:/data/parquet

volumes:
  db:
  parquet:
  
